version: '3'
services:
  node1:
    build: ./node
    ports: ['5001:5000']
    environment:
      - NODE_NAME=node1
      - PEERS=http://node2:5000,http://node3:5000
    networks:
      - blockchain-net

  node2:
    build: ./node
    ports: ['5002:5000']
    environment:
      - NODE_NAME=node2
      - PEERS=http://node1:5000,http://node3:5000
    networks:
      - blockchain-net

  node3:
    build: ./node
    ports: ['5003:5000']
    environment:
      - NODE_NAME=node3
      - PEERS=http://node1:5000,http://node2:5000
    networks:
      - blockchain-net

networks:
  blockchain-net:
    driver: bridge